# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

# Email notifications
notifications:
  email:
    on_success: change
    on_failure: change


#before_deploy:
#- R CMD INSTALL .

#deploy:
#  provider: script
#  script: Rscript -e 'pkgdown::deploy_site_github()'
#  skip_cleanup: true

# covr is not a dependency for the package. So, install it explicitly
# RUnit required for Rd xref checking. Also force its install
#r_binary_packages:
#  - covr
#  - RUnit

#after_success:
#  - Rscript -e 'covr::codecov()'
